import { StyleSheet } from "react-native";
import { THEME } from "./constants";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: THEME.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    backgroundColor: THEME.white,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF2F7",
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.background,
  },
  headerText: { flex: 1, marginHorizontal: 14 },
  headerTitle: { fontSize: 24, fontWeight: "800", color: THEME.textPrimary },
  headerSubtitle: { marginTop: 2, fontSize: 13, color: THEME.textSecondary },
  content: { padding: 20, paddingBottom: 20 },
  contentHorizontal: { paddingHorizontal: 20 },
  searchRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  searchBar: {
    flex: 1,
    height: 56,
    borderRadius: 28,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: THEME.white,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  searchInput: { flex: 1, marginLeft: 10, fontSize: 15, color: THEME.textPrimary },
  filterButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.white,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  filterPills: { gap: 10, paddingTop: 16, paddingBottom: 10 },
  filterPill: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: THEME.white,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  filterPillActive: { backgroundColor: THEME.primary, borderColor: THEME.primary },
  filterPillText: { fontSize: 13, fontWeight: "700", color: THEME.textSecondary },
  filterPillTextActive: { color: THEME.white },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 6 },
  statsCard: {
    width: "47%",
    minHeight: 100,
    borderRadius: 18,
    padding: 16,
    backgroundColor: THEME.white,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  statsIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  statsValue: { fontSize: 22, fontWeight: "800" },
  statsLabel: { marginTop: 4, fontSize: 12, color: THEME.textSecondary },
  sectionLabel: {
    marginTop: 24,
    marginBottom: 14,
    fontSize: 18,
    fontWeight: "800",
    color: THEME.textPrimary,
  },
  loadingWrap: {
    paddingVertical: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  listContent: { paddingBottom: 110 },
  listFooterSpace: { height: 12 },
  card: {
    backgroundColor: THEME.white,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHeader: { flexDirection: "row", alignItems: "flex-start" },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DDEBFF",
  },
  avatarText: { fontSize: 18, fontWeight: "800", color: THEME.primary },
  cardBody: { flex: 1, marginLeft: 14 },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  name: { flex: 1, fontSize: 16, fontWeight: "800", color: THEME.textPrimary },
  statusBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  statusText: { fontSize: 11, fontWeight: "800" },
  infoRow: { flexDirection: "row", alignItems: "center", marginTop: 6 },
  infoText: { marginLeft: 8, fontSize: 13, color: THEME.textSecondary },
  permissionsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
  permissionChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  permissionChipText: { fontSize: 12, fontWeight: "700" },
  noPermissionChip: { backgroundColor: "#F3F4F6" },
  noPermissionText: { color: THEME.textSecondary },
  actionRow: { flexDirection: "row", gap: 8, marginTop: 16, alignItems: "stretch" },
  actionButton: {
    minWidth: 0,
    paddingHorizontal: 12,
  },
  actionButtonText: {
    flexShrink: 1,
  },
  outlineButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.border,
    backgroundColor: THEME.white,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  outlineButtonText: { fontSize: 12, fontWeight: "700", color: THEME.primary },
  neutralButtonText: { fontSize: 12, fontWeight: "700", color: THEME.textSecondary },
  resendButton: {
    flex: 1.2,
  },
  moreButton: {
    flex: 0.85,
  },
  primaryButton: {
    flex: 1.15,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: THEME.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  primaryButtonText: { fontSize: 12, fontWeight: "700", color: THEME.white },
  buttonDisabled: {
    backgroundColor: "#E5E7EB",
    borderColor: "#E5E7EB",
  },
  buttonDisabledText: {
    color: THEME.textSecondary,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: THEME.white,
    borderRadius: 20,
    paddingVertical: 36,
    paddingHorizontal: 24,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF2F7",
  },
  emptyTitle: { marginTop: 14, fontSize: 16, fontWeight: "700", color: THEME.textPrimary },
  emptyText: {
    marginTop: 6,
    textAlign: "center",
    fontSize: 13,
    color: THEME.textSecondary,
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.success,
    shadowColor: THEME.success,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: THEME.overlay,
  },
  modalWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    borderRadius: 24,
    backgroundColor: THEME.white,
    padding: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  modalTitle: { fontSize: 19, fontWeight: "800", color: THEME.textPrimary },
  modalSubtitle: { marginTop: 4, fontSize: 13, color: THEME.textSecondary },
  modalLoading: {
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  permissionList: { gap: 14 },
  permissionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    borderWidth: 1,
    borderColor: "#EEF2F7",
    borderRadius: 16,
    padding: 14,
  },
  permissionTextWrap: { flex: 1 },
  permissionTitle: { fontSize: 15, fontWeight: "700", color: THEME.textPrimary },
  permissionDescription: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: THEME.textSecondary,
  },
  modalActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  modalSecondaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: THEME.border,
    alignItems: "center",
    justifyContent: "center",
  },
  modalSecondaryButtonText: { fontSize: 14, fontWeight: "700", color: THEME.textPrimary },
  modalPrimaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: THEME.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  modalPrimaryButtonText: { fontSize: 14, fontWeight: "700", color: THEME.white },
});
